TESTS				:= Tests/Assembler/
SOURCES				:= $(TESTS)and.asm $(TESTS)equals.asm $(TESTS)greater.asm $(TESTS)greaterEquals.asm $(TESTS)if.asm $(TESTS)less.asm $(TESTS)lessEquals.asm $(TESTS)notEquals.asm $(TESTS)or.asm
HEADERS				:= 

TARGET				?= arduino_due
SERIAL_PORT			?= /dev/ttyACM0
CONSOLE_BAUDRATE	?= 2400

HWLIB             	:= ../../hwlib
include           	$(HWLIB)/makefile.inc